version: "3"
services:
    db:
      container_name: db_suite5
      image: mysql
      ports:
       - "3306:3306"
      environment:
         - MYSQL_ROOT_PASSWORD=mysql
         - MYSQL_DATABASE=db

      volumes:
         - $PWD/db:/docker-entrypoint-initdb.d/:ro